"""initial schema

Revision ID: 233f9e042722
Revises:
Create Date: 2026-10-08 08:13:02.627466

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "233f9e042722"
down_revision: str | None = None
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("lineage_key", sa.String(length=128), nullable=True),
        sa.Column("storage_ref", sa.String(length=1000), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifacts_lineage", "artifacts", ["project_id", "type", "lineage_key"], unique=False
    )
    op.create_index(op.f("ix_artifacts_lineage_key"), "artifacts", ["lineage_key"], unique=False)
    op.create_index(op.f("ix_artifacts_type"), "artifacts", ["type"], unique=False)
    op.create_index("ix_artifacts_type_created", "artifacts", ["type", "created_at"], unique=False)
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("storage_ref", sa.String(length=1000), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("license_info", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Double(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False)
    op.create_index(op.f("ix_assets_source"), "assets", ["source"], unique=False)
    op.create_index(op.f("ix_assets_type"), "assets", ["type"], unique=False)
    op.create_index("ix_assets_type_source", "assets", ["type", "source"], unique=False)
    op.create_table(
        "llm_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index(op.f("ix_llm_cache_expires_at"), "llm_cache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_llm_cache_model"), "llm_cache", ["model"], unique=False)
    op.create_index(op.f("ix_llm_cache_provider"), "llm_cache", ["provider"], unique=False)
    op.create_table(
        "niches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_niches_name"), "niches", ["name"], unique=True)
    op.create_table(
        "provider_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.String(length=200), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("usage_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provider_usage_job", "provider_usage", ["job_id", "requested_at"], unique=False
    )
    op.create_index(op.f("ix_provider_usage_job_id"), "provider_usage", ["job_id"], unique=False)
    op.create_index(op.f("ix_provider_usage_model"), "provider_usage", ["model"], unique=False)
    op.create_index(
        op.f("ix_provider_usage_provider"), "provider_usage", ["provider"], unique=False
    )
    op.create_index(op.f("ix_provider_usage_purpose"), "provider_usage", ["purpose"], unique=False)
    op.create_index(
        op.f("ix_provider_usage_requested_at"), "provider_usage", ["requested_at"], unique=False
    )
    op.create_index(op.f("ix_provider_usage_success"), "provider_usage", ["success"], unique=False)
    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_providers_enabled"), "providers", ["enabled"], unique=False)
    op.create_index(op.f("ix_providers_kind"), "providers", ["kind"], unique=False)
    op.create_index(op.f("ix_providers_name"), "providers", ["name"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("niche_id", sa.String(length=36), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("target_audience", sa.String(length=200), nullable=True),
        sa.Column("publishing_frequency_per_week", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["niche_id"],
            ["niches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("external_channel_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channels_external_channel_id"), "channels", ["external_channel_id"], unique=True
    )
    op.create_index(op.f("ix_channels_status"), "channels", ["status"], unique=False)
    op.create_table(
        "pipeline_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("input_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("output_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_pipeline_jobs_status"), "pipeline_jobs", ["status"], unique=False)
    op.create_index(
        "ix_pipeline_jobs_status_type", "pipeline_jobs", ["status", "type"], unique=False
    )
    op.create_index(op.f("ix_pipeline_jobs_type"), "pipeline_jobs", ["type"], unique=False)
    op.create_table(
        "topic_clusters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("subscribers", sa.Integer(), nullable=False),
        sa.Column("total_views", sa.Integer(), nullable=False),
        sa.Column("total_videos", sa.Integer(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_metrics_channel_id"), "channel_metrics", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_channel_metrics_snapshot_at"), "channel_metrics", ["snapshot_at"], unique=False
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["pipeline_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_events_created_at"), "job_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("cluster_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["topic_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_name"), "topics", ["name"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("external_video_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False)
    op.create_index(
        op.f("ix_videos_external_video_id"), "videos", ["external_video_id"], unique=True
    )
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    op.create_table(
        "content_opportunities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=True),
        sa.Column("cluster_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("angle", sa.Text(), nullable=True),
        sa.Column("content_gap", sa.Text(), nullable=True),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["topic_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_opportunities_project_id"),
        "content_opportunities",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_opportunities_score"), "content_opportunities", ["score"], unique=False
    )
    op.create_index(
        op.f("ix_content_opportunities_status"), "content_opportunities", ["status"], unique=False
    )
    op.create_table(
        "video_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("average_view_duration_seconds", sa.Double(), nullable=True),
        sa.Column("click_through_rate", sa.Double(), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_metrics_snapshot_at"), "video_metrics", ["snapshot_at"], unique=False
    )
    op.create_index(op.f("ix_video_metrics_video_id"), "video_metrics", ["video_id"], unique=False)
    op.create_index(
        "ix_video_metrics_video_snapshot",
        "video_metrics",
        ["video_id", "snapshot_at"],
        unique=False,
    )
    op.create_table(
        "content_briefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["content_opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_briefs_opportunity_id"), "content_briefs", ["opportunity_id"], unique=True
    )
    op.create_index(op.f("ix_content_briefs_status"), "content_briefs", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("opportunity_id", sa.String(length=36), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["content_opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["content_opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_documents_source_id"), "research_documents", ["source_id"], unique=False
    )
    op.create_table(
        "research_claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("research_document_id", sa.String(length=36), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("support_status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_document_id"],
            ["research_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_claims_research_document_id"),
        "research_claims",
        ["research_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_claims_research_document_id"), table_name="research_claims")
    op.drop_table("research_claims")
    op.drop_index(op.f("ix_research_documents_source_id"), table_name="research_documents")
    op.drop_table("research_documents")
    op.drop_table("sources")
    op.drop_index(op.f("ix_content_briefs_status"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_opportunity_id"), table_name="content_briefs")
    op.drop_table("content_briefs")
    op.drop_index("ix_video_metrics_video_snapshot", table_name="video_metrics")
    op.drop_index(op.f("ix_video_metrics_video_id"), table_name="video_metrics")
    op.drop_index(op.f("ix_video_metrics_snapshot_at"), table_name="video_metrics")
    op.drop_table("video_metrics")
    op.drop_index(op.f("ix_content_opportunities_status"), table_name="content_opportunities")
    op.drop_index(op.f("ix_content_opportunities_score"), table_name="content_opportunities")
    op.drop_index(op.f("ix_content_opportunities_project_id"), table_name="content_opportunities")
    op.drop_table("content_opportunities")
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_external_video_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_topics_name"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_created_at"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_channel_metrics_snapshot_at"), table_name="channel_metrics")
    op.drop_index(op.f("ix_channel_metrics_channel_id"), table_name="channel_metrics")
    op.drop_table("channel_metrics")
    op.drop_table("topic_clusters")
    op.drop_index(op.f("ix_pipeline_jobs_type"), table_name="pipeline_jobs")
    op.drop_index("ix_pipeline_jobs_status_type", table_name="pipeline_jobs")
    op.drop_index(op.f("ix_pipeline_jobs_status"), table_name="pipeline_jobs")
    op.drop_table("pipeline_jobs")
    op.drop_index(op.f("ix_channels_status"), table_name="channels")
    op.drop_index(op.f("ix_channels_external_channel_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_providers_name"), table_name="providers")
    op.drop_index(op.f("ix_providers_kind"), table_name="providers")
    op.drop_index(op.f("ix_providers_enabled"), table_name="providers")
    op.drop_table("providers")
    op.drop_index(op.f("ix_provider_usage_success"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_requested_at"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_purpose"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_provider"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_model"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_job_id"), table_name="provider_usage")
    op.drop_index("ix_provider_usage_job", table_name="provider_usage")
    op.drop_table("provider_usage")
    op.drop_index(op.f("ix_niches_name"), table_name="niches")
    op.drop_table("niches")
    op.drop_index(op.f("ix_llm_cache_provider"), table_name="llm_cache")
    op.drop_index(op.f("ix_llm_cache_model"), table_name="llm_cache")
    op.drop_index(op.f("ix_llm_cache_expires_at"), table_name="llm_cache")
    op.drop_table("llm_cache")
    op.drop_index("ix_assets_type_source", table_name="assets")
    op.drop_index(op.f("ix_assets_type"), table_name="assets")
    op.drop_index(op.f("ix_assets_source"), table_name="assets")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index("ix_artifacts_type_created", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_type"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_lineage_key"), table_name="artifacts")
    op.drop_index("ix_artifacts_lineage", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
