"""provider usage metadata + discovery cache

Revision ID: 3a18452d2603
Revises: 233f9e042722
Create Date: 2026-10-08 15:31:22.554037

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a18452d2603"
down_revision: str | None = "233f9e042722"
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index(
        op.f("ix_discovery_cache_endpoint"), "discovery_cache", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_cache_expires_at"), "discovery_cache", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_cache_provider"), "discovery_cache", ["provider"], unique=False
    )
    op.add_column("provider_usage", sa.Column("metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_usage", "metadata")
    op.drop_index(op.f("ix_discovery_cache_provider"), table_name="discovery_cache")
    op.drop_index(op.f("ix_discovery_cache_expires_at"), table_name="discovery_cache")
    op.drop_index(op.f("ix_discovery_cache_endpoint"), table_name="discovery_cache")
    op.drop_table("discovery_cache")
    # ### end Alembic commands ###
