"""source cache for research plane

Revision ID: 825b2b619896
Revises: 3a18452d2603
Create Date: 2026-10-08 18:40:24.925408

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "825b2b619896"
down_revision: str | None = "3a18452d2603"
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_cache",
        sa.Column("url_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("canonical_url", sa.String(length=2000), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("url_fingerprint"),
    )
    op.create_index(
        op.f("ix_source_cache_expires_at"), "source_cache", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_source_cache_status"), "source_cache", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_cache_status"), table_name="source_cache")
    op.drop_index(op.f("ix_source_cache_expires_at"), table_name="source_cache")
    op.drop_table("source_cache")
    # ### end Alembic commands ###
